######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 5 19:14:11 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += breakout.h breakout_canvas.h
SOURCES += breakout.cpp breakout_canvas.cpp main.cpp
